import Head from 'next/head'
import Header from '../header'
import Footer from '../footer'
import Backtop from '../backtop'
import styles from './GlobalLayout.module.css'

const GlobalLayout = (props) => {
    const { children, title, titleText, homebj , topHeight } = props
    const headTitle = title + '-渔夫个人笔记'
    return (
        <>
            <Head>
                <title>{ headTitle }</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header titleText={ titleText } homebj={ homebj } />
                <div className={`${styles.content} center`} >
                    { children }
                </div>
            </main>
            <Backtop />
            <Footer/>
        </>
    )
}


export default GlobalLayout